name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Android Core Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev ccache
          sudo apt-get install -y libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
          pip install --upgrade pip
          pip install buildozer cython

      # This runs the direct build command locally inside the runner window
      - name: Build with Buildozer
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
        run: |
          yes | buildozer -v android debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app-apk
          path: bin/*.apk
